doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        url: '%env(DATABASE_URL)%'
        dbname: '%env(MYSQL_DATABASE)%'
        host: '%env(MYSQL_HOST)%'
        port: '%env(MYSQL_PORT)%'
        user: '%env(MYSQL_USER)%'
        password: '%env(MYSQL_PASSWORD)%'
        driver: pdo_mysql
        server_version: '%env(MYSQL_VERSION)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)

        # if the url option is specified, it will override the above config
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
