doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        url: '%env(DATABASE_URL)%'
        dbname: 'hugo_teste'
        host: 'localhost'
        port: 3306
        user: 'hugo_teste'
        password: 'Teste123!#'
        driver: pdo_mysql
        server_version: '5.7'
        #url:'mysql://hugo_teste:Teste123%21%23@127.0.0.1:3306/esn_trips?serverVersion=5.7'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)

        # if the url option is specified, it will override the above config
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
