twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - 'bootstrap_4_layout.html.twig'

    globals:
        project_title: '%env(TITLE)%'
        project_company: '%env(COMPANY)%'
        home_path: '/trip/public'